### ISSUE TITLE
onChangeComplete does not capture current color

### ISSUE THREAD

**Issue by evertoont** [hello-pangea/color-picker#2]
Using the onChangeComplete function, the color passed is always the one of the past state and never the one of the current state, being necessary to make a double click on the color to capture the correct hex of the color.

![Screenshot from 2022-09-13 14-30-10](https://user-images.githubusercontent.com/55769021/189971009-389552fb-adb5-4bc8-babb-79b7acc11b99.jpg)

**Comment by josephinebienes** [comment]
Just downloaded it today, and I also have the same issue.

**Comment by spezzino** [comment]
this might be the problem
https://github.com/hello-pangea/color-picker/blob/main/src/context/useColor.tsx#L62-L64

I think it should be passing newColors instead of colors

**Comment by Xhale1** [comment]
Fixed in #6 

Releasing a new version to npm now.

Thanks all for finding this!
