### ISSUE TITLE
ChromePicker inline svg not working

### ISSUE THREAD

**Issue by spezzino** [hello-pangea/color-picker#3]
v3.1.0

Tried the ChromePicker in my project, and noticed the unfold icon is inlined incorrectly

<img width="227" alt="image" src="https://user-images.githubusercontent.com/2013367/190551596-e06ec614-34ef-4bfa-84df-beffe8f40dcc.png">

<img width="201" alt="image" src="https://user-images.githubusercontent.com/2013367/190551681-a8d7a9b0-dab1-4c47-9026-65327c5090b7.png">

Output in color-picker.esm.js
```
var UnfoldMoreHorizontalIcon = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"><path d=\"M12,18.17L8.83,15L7.42,16.41L12,21L16.59,16.41L15.17,15M12,5.83L15.17,9L16.58,7.59L12,3L7.41,7.59L8.83,9L12,5.83Z\" /></svg>";
```

**Comment by Xhale1** [comment]
Closed in #5, thanks for your work on this!
